Chore/code review
snehaSaraJohn/web-puzzle-tmo pull request #5
Opened 2023-10-31 06:11 UTC by snehaSaraJohn

2023-11-03 00:59 UTC, SiddhuJajoo commented
@snehaSaraJohn Add screenshots / screen recording for local testing, Lint success and test cases success.

2023-11-03 05:19 UTC, snehaSaraJohn commented
> @snehaSaraJohn Add screenshots / screen recording for local testing, Lint success and test cases success.

@SiddhuJajoo Added screen shots and videos

2023-11-05 04:33 UTC, SiddhuJajoo requested changes
- PR must have some valid name which will mention what are you trying to achieve in that PR
- PR must have short description which will tell what is done
- All commits should be squashed to single commit
- All testing screenshots/ Screen recording must be attached in the PR instead of code review / pushing in the repo.

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +1.   Issue: `formateDate()` method  used for date format in `book-search.component.html`
Check this file in preview mode of visual studio. 
Give solutions for all mentioned issues in same format(Currently its not consistent) and check small grammatical mistakes like new sentence should start with capital letter.

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +    Before Implementation :![Before_correcting_mobile_ux](image.png)
Screenshots won't be visible in Preview mode so attach all screenshots and screen recordings in pull request.

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +    - addBookToReadingList
I didn't understand reference of following in 4th point
```
- addBookToReadingList
 - searchExample
 - searchBooks
```

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +5.  Issue: ngSubmit used instead of submit as its a reactive module
Mention issue and then solution with file name.

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +Solution:Added async pipe in 'book-search.component.html' file line#33 to avoid memory leak. Async pipe will automatically unsubscribe the observable once component is destroyed
I think since you have mentioned memory leak in issue you can remove it from solution. Rephrase this sentence so it won't feel repetitive

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +   --For implementation,mat Spinner used in Book-search.component.html and changes are maded to "loaded"flag  in "book.reducer.ts"
rephrase.
`maded` `loaded` flag - does not make sense

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +- **Ran authomated scan using light house and corrected issues.**
spelling correction

2023-11-05 04:33 UTC, SiddhuJajoo commented on CODE_REVIEW.md
> +  E2e result:![e2e_result](e2e_test.png),![e2e_readinglist_result](dist\cypress\apps\okreads-e2e\videos\reading-list.spec.ts.mp4),![e2e_searchbook_result](dist\cypress\apps\okreads-e2e\videos\search-
Screen recording is not loading in preview mode.
![image](https://github.com/snehaSaraJohn/web-puzzle-tmo/assets/44996907/3cfe34f3-f332-4ff3-a32a-57715f270aa0)

Add all testing screenshots as attachment in the PR.

2023-11-05 04:33 UTC, SiddhuJajoo commented on angular.json
> +            "styles": [
If no changes then revert this file

2023-11-05 04:33 UTC, SiddhuJajoo commented on apps/okreads-e2e/tsconfig.e2e.json
> +//   "compilerOptions": {
Do not commit commented code

2023-11-05 04:33 UTC, SiddhuJajoo commented on apps/okreads-e2e/tsconfig.e2e.json
> +    "outDir": "../../../dist/out-tsc",
Why is this change needed?

2023-11-05 04:33 UTC, SiddhuJajoo commented on changes.md
> +
Why is this file committed?

2023-11-05 04:33 UTC, SiddhuJajoo commented on libs/books/data-access/src/lib/+state/books.reducer.ts
> +  loaded: true
Why do we need to have initial state as `loaded: true`?

2023-11-06 13:30 UTC, closed without merging